version: "0.1"
services:
  cbdb-coordinator:
    container_name: cbdb-mdw
    image: cbdb-${CODEBASE_VERSION}:${OS_VERSION}
    ports:
    - "15432:5432"
    hostname: mdw
    tty: true
    networks:
      interconnect:
        ipv4_address: 10.5.0.10
    environment:
      MULTINODE: "true"
  cbdb-standby-coordinator:
    container_name: cbdb-smdw
    image: cbdb-${CODEBASE_VERSION}:${OS_VERSION}
    hostname: smdw
    tty: true
    networks:
      interconnect:
        ipv4_address: 10.5.0.11
  cbdb-segment-host-1:
    container_name: cbdb-sdw1
    image: cbdb-${CODEBASE_VERSION}:${OS_VERSION}
    hostname: sdw1
    tty: true
    networks:
      interconnect:
        ipv4_address: 10.5.0.12
  cbdb-segment-host-2:
    container_name: cbdb-sdw2
    image: cbdb-${CODEBASE_VERSION}:${OS_VERSION}
    hostname: sdw2
    tty: true
    networks:
      interconnect:
        ipv4_address: 10.5.0.13
networks:
  interconnect:
    name: cbdb-interconnect
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
